version: '2.6'

services:
  mysql:
    container_name: mysql_8.0
    image: mysql:8.0
    volumes:
      - /data/mysql:/var/lib/mysql
    command:
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
      --default-authentication-plugin=mysql_native_password
      --wait_timeout=2880000
      --interactive_timeout=2880000
      --max_connections=1000
      --key_buffer_size=10M
      --default_storage_engine=InnoDB
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'Mjolnir'
    restart: always